---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install apt packages
      become: yes
      apt:
        name: ['vim', 'jq', 'python3-pip']
        state: present
        update_cache: yes
        autoremove: yes
        autoclean: yes
    - name: install jupyter
      become: yes
      pip:
        name: jupyter
        state: present

