---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install pyOpenSSL locally to enable creating certs
      delegate_to: localhost
      become: yes
      pip:
        name: pyOpenSSL
        state: present
    - name: create certs path locally
      delegate_to: localhost
      become: yes
      file:
        path: certs
        state: directory
        owner: d
        group: d

# CREATE ROOT CA
    - name: create TLS rootca key locally
      delegate_to: localhost
      openssl_privatekey:
        path: certs/rootca.key
        size: 2048
        state: present
        type: RSA
    - name: create TLS rootca CSR locally
      delegate_to: localhost
      openssl_csr:
        path: certs/rootca.csr
        common_name: david-rootca
        privatekey_path: certs/rootca.key
        basic_constraints: "CA:true"
    - name: create TLS rootca cert locally --- you should manually add certs/rootca.pem to your browsers trusted root certs
      delegate_to: localhost
      openssl_certificate:
        path: certs/rootca.pem
        csr_path: certs/rootca.csr
        privatekey_path: certs/rootca.key
        provider: selfsigned

# CREATE CERTS FOR JupyterHub
    - name: create TLS key for jupyterhub locally
      delegate_to: localhost
      openssl_privatekey:
        path: certs/jupyterhub.key
        size: 2048
        state: present
        type: RSA
    - name: create TLS CSR for jupyterhub locally --- you should manually add \"127.0.0.1 local-dev\" to your /etc/hosts file
      delegate_to: localhost
      openssl_csr:
        path: certs/jupyterhub.csr
        common_name: local-dev
        privatekey_path: certs/jupyterhub.key
    - name: create TLS cert for jupyterhub locally
      delegate_to: localhost
      openssl_certificate:
        path: certs/jupyterhub.pem
        csr_path: certs/jupyterhub.csr
        ownca_path: certs/rootca.pem
        ownca_privatekey_path: certs/rootca.key
        provider: ownca

# COPY CERT FILES ONTO THE JupyterHub SERVER
    - name: create cert path
      become: yes
      file:
        path: /home/vagrant/certs
        state: directory
        owner: vagrant
        group: vagrant
        mode: u=rwx,g=r,o=r
    - name: copy TLS key for JupyterHub to use
      become: yes
      copy:
        src: certs/jupyterhub.key
        dest: /home/vagrant/certs/jupyterhub.key
        owner: vagrant
        group: vagrant
        mode: u=rw
    - name: copy TLS cert for JupyterHub to use
      become: yes
      copy:
        src: certs/jupyterhub.pem
        dest: certs/jupyterhub.pem
        owner: vagrant
        group: vagrant
        mode: u=rw,g=r,o=r

# OTHER INSTALL STUFF
    - name: upgrade all apt packages
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
    - name: install apt packages
      become: yes
      apt:
        name: ['vim', 'jq', 'python3-pip', 'npm', 'nodejs']
        state: present
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes
        autoclean: yes
    - name: install jupyterhub proxy
      become: yes
      npm:
        name: configurable-http-proxy
        global: yes
        state: present
    - name: install jupyterhub
      become: yes
      pip:
        name: ['jupyterhub', 'notebook']
        state: present
    - name: create jupyter daemon
      import_role:
        name: tumf.systemd-service
      become: yes
      vars:
        systemd_service_name: jupyterhub
        systemd_service_Unit_Description: jupyterhub
        systemd_service_Service_Type: simple
        systemd_service_Service_PIDFile: /run/jupyterhub.pid
        systemd_service_Service_ExecStart: /usr/local/bin/jupyterhub --ip 0.0.0.0 --port 8888 --ssl-key /home/vagrant/certs/jupyterhub.key --ssl-cert /home/vagrant/certs/jupyterhub.pem
        systemd_service_Service_User: root
        systemd_service_Service_Group: root
        systemd_service_Service_WorkingDirectory: /home/vagrant
        systemd_service_Service_Restart: always
        systemd_service_Service_RestartSec: 10
        systemd_service_Install_WantedBy: multi-user.target
    - name: enable jupyterhub service -- autostart on boot
      become: yes
      service:
        name: jupyterhub
        enabled: yes
        state: started
...

