---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install vim
      become: yes
      apt:
        name: vim
        state: present
        update_cache: yes
    - name: install jq
      become: yes
      apt:
        name: jq
        state: present
        update_cache: yes
    - name: remove unused apt packages
      become: yes
      apt:
        autoremove: yes

