---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: upgrade all apt packages
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600
    - name: install apt packages
      become: yes
      apt:
        name: ['vim', 'jq', 'python3-pip', 'npm', 'nodejs-legacy']
        state: present
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes
        autoclean: yes
    - name: install jupyterhub proxy
      npm:
        name: configurable-http-proxy
        global: yes
        state: present
    - name: install jupyter
      become: yes
      pip:
        name: ['jupyterhub', 'notebook']
        state: present

